### ISSUE TITLE
Modify flattening function

### ISSUE THREAD

**Issue by drewoldag** [LSSTDESC/rail_deepdisc#14]
Currently the flattening function seems rather specific to one particular data type. There are a few things we could consider to improve the usability of this pre-processing step.

Consider the input type. Should choose one of the following: 
- [ ] path to a directory containing files to be flattened
- [ ] path to a manifest file that contains a list of files to be flattened

Make the pre-processing self contained:
- [ ] Return a path to the flattened image file (saved as <filename>.hdf5)
- [ ] Return a path to the metadata file (saved as <filename_metadata>.json)
- [ ] Examining the code in `flatten.py`, it looks like there was some additional pre-processing before this step, can we consolidate the pre-processing? 

Ensure that we are no longer stashing metadata on the end of the flattened image arrays. 
- [ ] All metadata should be in the metadata.json file, Nothing should be included in the images. 
- [ ] Encapsulate the creation of the metadata file. If we discover later that we need to take a new approach to reading in the metadata, having this logically isolated will be good. Something like `def output_metadata(list_of_dict): #output as .json, or sqlite, or ...`.

**Comment by drewoldag** [comment]
We should abstract any reshaping logic that has already been implemented as well, so that the flattening and the unflattening code live in the same module (or at least close to each other)

**Comment by grantmerz** [comment]
I think we can put this on the backburner for now.  The logic to flatten the images is really simple (just `np.flatten()`).  We assume that the images are shaped [CxHxW] before calling flatten, and then we reshape to that shape before caching them.  The metadata is now separated, so we don't need to consider unflattening it

**Comment by drewoldag** [comment]
This is ultimately part of issue https://github.com/lincc-frameworks/deepdisc/issues/23 in deepdisc. Closing this as basically a duplicate.
