### ISSUE TITLE
Cleaning: Variable Names

### ISSUE THREAD

**Issue by dougbrn** [LSSTDESC/rail_deepdisc#21]
Address Variable Name updates for the following comments (made by @drewoldag):

- [x] https://github.com/LSSTDESC/rail_deepdisc/pull/15#discussion_r1416672622

- [x] https://github.com/LSSTDESC/rail_deepdisc/pull/15#discussion_r1416661916

- [x] https://github.com/LSSTDESC/rail_deepdisc/pull/15#discussion_r1416653551

- [x] https://github.com/LSSTDESC/rail_deepdisc/pull/15#discussion_r1416653151

- [x] https://github.com/LSSTDESC/rail_deepdisc/pull/15#discussion_r1416652645

- [x] https://github.com/LSSTDESC/rail_deepdisc/pull/15#discussion_r1416652357

**Comment by drewoldag** [comment]
Closing this as it was taken care of in PR #31
