### ISSUE TITLE
Allow splitting data/metadata into training and evaluation sets

### ISSUE THREAD

**Issue by drewoldag** [LSSTDESC/rail_deepdisc#34]
This should actually be fairly straightforward. We'll need to create a new StageParameter that will define the percentage of training vs. evaluation data. Then we will need to make use of that percentage to define slices of the metadata to be passed to the training and testing functions. 

An example StageParameter might look something like this:
```
config_options.update(
    ...
    training_percent = Param(float, 0.8, required=False, msg="The percentage of input_data to use for training"),
    ...
)
```

Then to make use of this in the `train` function, we can define to Python slice objects and use them to pass portions of the `metadata` list to the `build_detection_train_loader` and `build_detection_test_loader`. Something like this:
```
# define the slices
num_images = len(metadata)
train_slice = slice( int(np.floor(num_images * config[training_percent])) )
test_slice = slice( int(np.floor(num_images * config[training_percent])) + 1, num_images )

# use the slices
loader_training = d2data.build_detection_train_loader(
    training_metadata[train_slice],  # <-- Use the training slice here
    mapper=mapper,
    total_batch_size=batch_size
)

loader_testing = d2data.build_detection_test_loader(
    training_metadata[test_slice],  # <-- Use the testing slice here
    mapper=mapper,
    total_batch_size=batch_size
)
```

**Comment by drewoldag** [comment]
@grantmerz to finalize the approach here, I would need confirmation about how you plan on using `loading_training` and `loader_testing`. I know that the use was in an early version of the repo, but I can't recall the details about how it's used.

**Comment by grantmerz** [comment]
Yeah this looks good and we don't need to mess with the caching at all.  loader_training goes into the trainer object and iterates over the training set, and loader_testing goes into the lossHook and iterates over the evaluation set.  Naming convention is a bit confusing since detectron2 has the build_detection_test_loader function, but it's actually used for the "evaluation" set.
