### ISSUE TITLE
Remove estimator class that does not chunk metadata

### ISSUE THREAD

**Issue by drewoldag** [LSSTDESC/rail_deepdisc#50]
Once the estimator class that chunks input metadata has been vetted, we should remove to superfluous non-chunking code and rename the chunking estimator from `DeepDiscPDFEstimatorWithChunking` to `DeepDiscPDFEstimator`.

**Comment by grantmerz** [comment]
I think I'd like to keep the old class for now, since I may use it as the basis of new estimators with torch parallelization

**Comment by drewoldag** [comment]
Going to close this as "won't do" for now then.
